# Generated by Django 4.0.4 on 2022-05-06 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do ambiente')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'ambiente',
                'verbose_name_plural': 'ambientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do campus no SUAP')),
                ('sigla', models.CharField(max_length=255, unique=True, verbose_name='sigla do campus')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('thumbnail', models.ImageField(max_length=255, upload_to='', verbose_name='thumbnail')),
                ('active', models.BooleanField(verbose_name='ativo?')),
                ('homepage', models.BooleanField(default=True, verbose_name='listar na página principal?')),
            ],
            options={
                'verbose_name': 'campus',
                'verbose_name_plural': 'campi',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do componente no SUAP')),
                ('sigla', models.CharField(max_length=255, unique=True, verbose_name='sigla do componente')),
                ('descricao', models.CharField(max_length=512, verbose_name='descrição')),
                ('descricao_historico', models.CharField(max_length=512, verbose_name='descrição no histórico')),
                ('periodo', models.IntegerField(blank=True, null=True, verbose_name='período')),
                ('tipo', models.IntegerField(verbose_name='tipo')),
                ('optativo', models.BooleanField(verbose_name='optativo')),
                ('qtd_avaliacoes', models.IntegerField(verbose_name='qtd. avalições')),
            ],
            options={
                'verbose_name': 'componente',
                'verbose_name_plural': 'componentes',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do curso no SUAP')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='código do curso')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do curso')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('url_ppc', models.URLField(max_length=255, verbose_name='URL')),
                ('thumbnail', models.ImageField(max_length=255, upload_to='', verbose_name='thumbnail')),
                ('active', models.BooleanField(verbose_name='ativo?')),
                ('homepage', models.BooleanField(default=True, verbose_name='listar na página principal?')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('ano_mes', models.IntegerField(primary_key=True, serialize=False, verbose_name='período')),
            ],
            options={
                'verbose_name': 'período',
                'verbose_name_plural': 'períodos',
                'ordering': ['ano_mes'],
            },
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do pólo no SUAP')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome do pólo')),
            ],
            options={
                'verbose_name': 'pólo',
                'verbose_name_plural': 'pólos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='código da turma')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID da turma no SUAP')),
                ('semestre', models.SmallIntegerField(verbose_name='semestre')),
                ('sigla', models.CharField(max_length=8, verbose_name='sigla da turma')),
                ('turno', models.CharField(choices=[('N', 'Noturno'), ('V', 'Vespertino'), ('M', 'Matutino'), ('E', 'EAD'), ('D', 'Diurno'), ('I', 'Integral'), ('_', 'Desconhecido')], max_length=1, verbose_name='turno')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.campus', verbose_name='campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.curso', verbose_name='curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.periodo', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do diário no SUAP')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='código do diário')),
                ('situacao', models.CharField(max_length=255, verbose_name='situação')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('descricao_historico', models.CharField(max_length=255, verbose_name='descrição no histórico')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.componente', verbose_name='componente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'diário',
                'verbose_name_plural': 'diários',
                'ordering': ['codigo'],
            },
        ),
    ]
