# Generated by Django 4.0.5 on 2022-06-14 21:19

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['codigo'], 'verbose_name': 'turma', 'verbose_name_plural': 'turmas'},
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo?'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='optativo',
            field=models.BooleanField(blank=True, null=True, verbose_name='optativo'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='qtd_avaliacoes',
            field=models.IntegerField(blank=True, null=True, verbose_name='qtd. avalições'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.IntegerField(blank=True, null=True, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('(\\d{5})\\.(\\d)\\.(\\d{5})\\.(..)'))], verbose_name='código da turma'),
        ),
    ]
