# Generated by Django 4.1.4 on 2023-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_ambiente_deleted_ambiente_deleted_by_cascade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambiente",
            name="cor",
            field=models.CharField(
                help_text="Escolha uma cor em RGB. Ex.: <span style='background: #a154d0; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#a154d0</span> <span style='background: #438f4b; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#438f4b</span> <span style='background: #c90c0f; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#c90c0f</span> <span style='background: #c90c0f; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#c90c0f</span>",
                max_length=255,
                verbose_name="cor do ambiente",
            ),
        ),
        migrations.AlterField(
            model_name="historicalambiente",
            name="cor",
            field=models.CharField(
                help_text="Escolha uma cor em RGB. Ex.: <span style='background: #a154d0; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#a154d0</span> <span style='background: #438f4b; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#438f4b</span> <span style='background: #c90c0f; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#c90c0f</span> <span style='background: #c90c0f; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#c90c0f</span>",
                max_length=255,
                verbose_name="cor do ambiente",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinscricao",
            name="papel",
            field=models.CharField(
                choices=[
                    ("student", "Aluno"),
                    ("editingteacher", "Professor"),
                    ("teacher", "Tutor"),
                    ("manager", "Coordenador"),
                    ("coursecreator", "Conteudista"),
                ],
                max_length=256,
                verbose_name="papel",
            ),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="papel",
            field=models.CharField(
                choices=[
                    ("student", "Aluno"),
                    ("editingteacher", "Professor"),
                    ("teacher", "Tutor"),
                    ("manager", "Coordenador"),
                    ("coursecreator", "Conteudista"),
                ],
                max_length=256,
                verbose_name="papel",
            ),
        ),
    ]
