# Generated by Django 4.1.7 on 2023-04-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_alter_ambiente_cor_alter_historicalambiente_cor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambiente",
            name="cor_sutil",
            field=models.CharField(
                default="#a154d0",
                help_text="Escolha uma cor em RGB. Ex.: <span style='background: #ecdbf9; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#ecdbf9</span> <span style='background: #438f4b; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#438f4b</span> <span style='background: #c90c0f; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#c90c0f</span> <span style='background: #c90c0f; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#c90c0f</span>",
                max_length=255,
                verbose_name="cor sutil do ambiente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalambiente",
            name="cor_sutil",
            field=models.CharField(
                default="#a154d0",
                help_text="Escolha uma cor em RGB. Ex.: <span style='background: #ecdbf9; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#ecdbf9</span> <span style='background: #438f4b; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#438f4b</span> <span style='background: #c90c0f; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#c90c0f</span> <span style='background: #c90c0f; color: #fff; padding: 1px 5px; font-size: 95%; border-radius: 4px;'>#c90c0f</span>",
                max_length=255,
                verbose_name="cor sutil do ambiente",
            ),
            preserve_default=False,
        ),
    ]
