# Generated by Django 4.2.3 on 2023-08-01 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("a4", "0004_remove_usuario_email_escolar_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="grupo",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
        migrations.AddField(
            model_name="grupo",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="grupo",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Servidor (Docente)", "Servidor (Docente)"),
                    (
                        "Servidor (Técnico-Administrativo)",
                        "Servidor (Técnico-Administrativo)",
                    ),
                    ("Prestador de Serviço", "Prestador de Serviço"),
                    ("Aluno", "Aluno"),
                    ("desconhecido", "Desconhecido"),
                ],
                max_length=255,
                null=True,
                verbose_name="tipo",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalGrupo",
            fields=[
                (
                    "group_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=150, verbose_name="name"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical grupo",
                "verbose_name_plural": "historical grupos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
