# Generated by Django 4.2.4 on 2023-10-12 21:00

import a4.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a4", "0006_historicalusuario_last_json_usuario_last_json"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", a4.models.UsuarioManager()),
            ],
        ),
    ]
