# Generated by Django 4.0.2 on 2022-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Noturno'), (2, 'Vespertino'), (3, 'Matutino'), (5, 'EAD'), (6, 'Diurno'), (7, 'Integral')], verbose_name='turno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_academico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='e-Mail academico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_escolar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='e-Mail escolar'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_institucional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='e-Mail institucional'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_pessoal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='e-Mail pessoal'),
        ),
    ]
