# Generated by Django 3.1.2 on 2021-10-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaportal', '0003_solicitacao_status_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['descricao'], 'verbose_name': 'Campus', 'verbose_name_plural': 'Campi'},
        ),
        migrations.AddField(
            model_name='campus',
            name='homepage',
            field=models.BooleanField(default=True, verbose_name='Listar na página principal?'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='active',
            field=models.BooleanField(verbose_name='Ativo?'),
        ),
    ]
