# Generated by Django 4.2.3 on 2023-08-01 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "middleware",
            "0002_solicitacao_deleted_solicitacao_deleted_by_cascade_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsolicitacao",
            old_name="requisicao",
            new_name="recebido",
        ),
        migrations.RenameField(
            model_name="historicalsolicitacao",
            old_name="requisicao_header",
            new_name="recebido_header",
        ),
        migrations.RenameField(
            model_name="historicalsolicitacao",
            old_name="resposta",
            new_name="respondido",
        ),
        migrations.RenameField(
            model_name="historicalsolicitacao",
            old_name="resposta_header",
            new_name="respondido_header",
        ),
        migrations.RenameField(
            model_name="solicitacao",
            old_name="requisicao",
            new_name="recebido",
        ),
        migrations.RenameField(
            model_name="solicitacao",
            old_name="requisicao_header",
            new_name="recebido_header",
        ),
        migrations.RenameField(
            model_name="solicitacao",
            old_name="resposta",
            new_name="respondido",
        ),
        migrations.RenameField(
            model_name="solicitacao",
            old_name="resposta_header",
            new_name="respondido_header",
        ),
    ]
