# Generated by Django 4.2.4 on 2023-08-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middleware", "0003_remove_historicalsolicitacao_requisicao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="recebido",
            field=models.TextField(blank=True, null=True, verbose_name="JSON recebido"),
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="respondido",
            field=models.TextField(
                blank=True, null=True, verbose_name="JSON respondido"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="recebido",
            field=models.TextField(blank=True, null=True, verbose_name="JSON recebido"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="respondido",
            field=models.TextField(
                blank=True, null=True, verbose_name="JSON respondido"
            ),
        ),
    ]
