# Generated by Django 4.2.3 on 2023-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "middleware",
            "0003_rename_requisicao_historicalsolicitacao_recebido_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsolicitacao",
            name="enviado",
            field=models.TextField(blank=True, null=True, verbose_name="enviado"),
        ),
        migrations.AddField(
            model_name="historicalsolicitacao",
            name="enviado_header",
            field=models.JSONField(
                blank=True, null=True, verbose_name="cabeçalho enviado"
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="enviado",
            field=models.TextField(blank=True, null=True, verbose_name="enviado"),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="enviado_header",
            field=models.JSONField(
                blank=True, null=True, verbose_name="cabeçalho enviado"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="recebido",
            field=models.TextField(blank=True, null=True, verbose_name="recebido"),
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="recebido_header",
            field=models.JSONField(
                blank=True, null=True, verbose_name="cabeçalho recebido"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="respondido",
            field=models.TextField(blank=True, null=True, verbose_name="respondido"),
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="respondido_header",
            field=models.JSONField(
                blank=True, null=True, verbose_name="cabeçalho respondido"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="recebido",
            field=models.TextField(blank=True, null=True, verbose_name="recebido"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="recebido_header",
            field=models.JSONField(
                blank=True, null=True, verbose_name="cabeçalho recebido"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="respondido",
            field=models.TextField(blank=True, null=True, verbose_name="respondido"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="respondido_header",
            field=models.JSONField(
                blank=True, null=True, verbose_name="cabeçalho respondido"
            ),
        ),
    ]
