# Generated by Django 4.2.4 on 2023-08-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middleware", "0004_historicalsolicitacao_enviado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="enviado",
            field=models.TextField(blank=True, null=True, verbose_name="JSON enviado"),
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="recebido",
            field=models.TextField(blank=True, null=True, verbose_name="JSON recebido"),
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="respondido",
            field=models.TextField(blank=True, null=True, verbose_name="JSON respondido"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="enviado",
            field=models.TextField(blank=True, null=True, verbose_name="JSON enviado"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="recebido",
            field=models.TextField(blank=True, null=True, verbose_name="JSON recebido"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="respondido",
            field=models.TextField(blank=True, null=True, verbose_name="JSON respondido"),
        ),
    ]
