# Generated by Django 4.2.4 on 2023-08-02 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("middleware", "0005_alter_historicalsolicitacao_enviado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsolicitacao",
            name="enviado_header",
        ),
        migrations.RemoveField(
            model_name="historicalsolicitacao",
            name="recebido_header",
        ),
        migrations.RemoveField(
            model_name="historicalsolicitacao",
            name="respondido_header",
        ),
        migrations.RemoveField(
            model_name="solicitacao",
            name="enviado_header",
        ),
        migrations.RemoveField(
            model_name="solicitacao",
            name="recebido_header",
        ),
        migrations.RemoveField(
            model_name="solicitacao",
            name="respondido_header",
        ),
    ]
