# Generated by Django 4.2.3 on 2023-07-28 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import painel.models
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("painel", "0008_popup_historicalpopup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Papel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "nome",
                    models.CharField(max_length=256, verbose_name="nome do papel"),
                ),
                (
                    "sigla",
                    models.CharField(
                        blank=True, max_length=10, unique=True, verbose_name="sigla"
                    ),
                ),
                (
                    "contexto",
                    models.CharField(
                        choices=[("c", "Curso"), ("p", "Pólo")],
                        max_length=1,
                        verbose_name="contexto",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
            ],
            options={
                "verbose_name": "papel",
                "verbose_name_plural": "papéis",
                "ordering": ["sigla"],
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VinculoPolo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "colaborador",
                    models.ForeignKey(
                        limit_choices_to={
                            "tipo_usuario__in": [
                                "Prestador de Serviço",
                                "Servidor (Docente)",
                                "Servidor (Técnico-Administrativo)",
                            ]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_polos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        limit_choices_to={"contexto": "p"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="painel.papel",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="painel.polo"
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo no pólo",
                "verbose_name_plural": "vínculos nos pólos",
                "ordering": ["papel", "polo", "colaborador"],
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VinculoCurso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "colaborador",
                    models.ForeignKey(
                        limit_choices_to={
                            "tipo_usuario__in": [
                                "Prestador de Serviço",
                                "Servidor (Docente)",
                                "Servidor (Técnico-Administrativo)",
                            ]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_cursos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="painel.curso"
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        limit_choices_to={"contexto": "p"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="painel.papel",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo no curso",
                "verbose_name_plural": "vínculos nos cursos",
                "ordering": ["papel", "curso", "colaborador"],
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVinculoPolo",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={
                            "tipo_usuario__in": [
                                "Prestador de Serviço",
                                "Servidor (Docente)",
                                "Servidor (Técnico-Administrativo)",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"contexto": "p"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.papel",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.polo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo no pólo",
                "verbose_name_plural": "historical vínculos nos pólos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVinculoCurso",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={
                            "tipo_usuario__in": [
                                "Prestador de Serviço",
                                "Servidor (Docente)",
                                "Servidor (Técnico-Administrativo)",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.curso",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"contexto": "p"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.papel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo no curso",
                "verbose_name_plural": "historical vínculos nos cursos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPapel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "nome",
                    models.CharField(max_length=256, verbose_name="nome do papel"),
                ),
                (
                    "sigla",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, verbose_name="sigla"
                    ),
                ),
                (
                    "contexto",
                    models.CharField(
                        choices=[("c", "Curso"), ("p", "Pólo")],
                        max_length=1,
                        verbose_name="contexto",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical papel",
                "verbose_name_plural": "historical papéis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCursoPolo",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.curso",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="painel.polo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pólo do curso",
                "verbose_name_plural": "historical pólos do curso",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CursoPolo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("active", models.BooleanField(verbose_name="ativo?")),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="painel.curso"
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="painel.polo"
                    ),
                ),
            ],
            options={
                "verbose_name": "pólo do curso",
                "verbose_name_plural": "pólos do curso",
                "ordering": ["curso", "polo"],
            },
            bases=(painel.models.ActiveMixin, models.Model),
        ),
    ]
