# Generated by Django 4.2.4 on 2023-08-02 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("painel", "0011_alter_papel_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambiente",
            name="sigla",
        ),
        migrations.RemoveField(
            model_name="historicalambiente",
            name="sigla",
        ),
    ]
