#!/usr/bin/env bash

source _/functions

cp -r ./confs/examples/* ./confs/enabled

echo ""; echo_info "Parar o mundo"
_/down


if ! grep -q 'PORTAL-AVA' /etc/hosts; then
    echo '

######################################################################
## PORTAL-AVA
######################################################################
127.0.0.2    ava

    ' | sudo tee -a /etc/hosts
fi

for repo in 'moodle__block_suapattendance' 'moodle__local_suap' 'moodle__auth_suap' 'moodle__theme_maeve' 'moodle__image'; do
    if [[ ! -d ../$repo ]]; then
        echo "Clonando $repo"
        git clone https://github.com/cte-zl-ifrn/$repo.git ../$repo
    else
        echo "Repositório $repo já foi clonado anteriormente?"
    fi
done

if [[ ! -d ../moodle__theme_moove ]]; then
    echo "Baixando o $repo"
    wget https://moodle.org/plugins/download.php/28087/theme_moove_moodle41_2022112801.zip \
    && unzip theme_moove_moodle41_2022112801.zip -d ../ \
    && mv ../moove ../moodle__theme_moove \
    && rm theme_moove_moodle41_2022112801.zip
else
    echo "Repositório $repo já foi clonado anteriormente?"
fi

if [[ ! -d ../django-adminlte3 ]]; then
    echo "Clonando $repo"
    git clone https://github.com/kelsoncm/django-adminlte3.git ../django-adminlte3
else
    echo "Repositório $repo já foi clonado anteriormente?"
fi



mkdir -p volumes/moodle_data && chmod 777 volumes/moodle_data

echo ""; echo_info "Sobe o cache e o db em background"
_/backs

echo ""; echo_info "Construir as imagens"
_/build

echo ""; echo_info "Reiniciando o mundo novamente"
_/up
