#!/usr/bin/env bash

source _/functions

cp -r ./confs/examples ./confs/enabled

echo ""; echo_info "Parar o mundo"
_/down


if ! grep -q 'PAINEL-AVA' /etc/hosts; then
    echo '

######################################################################
## PAINEL-AVA
######################################################################
127.0.0.2    ava

    ' | sudo tee -a /etc/hosts
fi

pwd=`pwd`
for repo in 'moodle__local_suap' 'moodle__auth_suap' 'moodle__enrol_suap' 'moodle__theme_moove' 'moodle__block_suapattendance' 'moodle__image' 'moodle-tool_suap_archiver'; do
    if [[ ! -d ../$repo ]]; then
        echo "Clonando $repo"
        git clone https://github.com/cte-zl-ifrn/$repo.git ../$repo
        if [ "$repo" = "moodle__theme_moove" ]; then
            cd ../$repo
            git checkout ctezlifrn
            cd $pwd
        fi
    else
        echo "Repositório $repo já foi clonado anteriormente?"
    fi
done

for repo in 'django-adminlte3' 'moodle__profilefield_json'; do
    if [[ ! -d ../$repo ]]; then
        echo "Clonando $repo"
        git clone https://github.com/kelsoncm/$repo.git ../$repo
    else
        echo "Repositório $repo já foi clonado anteriormente?"
    fi
done


if [[ ! -d ../github ]]; then
    echo "Clonando github"
    git clone https://github.com/kelsoncm/github.git ../github
else
    echo "Repositório github já foi clonado anteriormente?"
fi

mkdir -p volumes/moodle_data && chmod 777 volumes/moodle_data

echo ""; echo_info "Sobe o cache e o db em background"
_/backs

echo ""; echo_info "Construir as imagens"
_/build

echo ""; echo_info "Reiniciando o mundo novamente"
_/restart
_/logs
