# Generated by Django 4.0.5 on 2022-06-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='quando ocorreu')),
                ('requisicao', models.TextField(blank=True, null=True, verbose_name='requisição')),
                ('requisicao_header', models.JSONField(blank=True, null=True, verbose_name='cabeçalho da requisição')),
                ('requisicao_invalida', models.TextField(blank=True, null=True, verbose_name='requisição inválida')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='resposta')),
                ('resposta_header', models.JSONField(blank=True, null=True, verbose_name='cabeçalho da resposta')),
                ('resposta_invalida', models.TextField(blank=True, null=True, verbose_name='resposta inválida')),
                ('status', models.CharField(blank=True, choices=[('S', 'Sucesso'), ('F', 'Falha')], max_length=256, null=True, verbose_name='status')),
                ('status_code', models.CharField(blank=True, max_length=256, null=True, verbose_name='status code')),
                ('diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.diario')),
            ],
            options={
                'verbose_name': 'solicitação',
                'verbose_name_plural': 'solicitações',
                'ordering': ['id'],
            },
        ),
    ]
