# Generated by Django 4.0.5 on 2022-06-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0002_solicitacao_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['-timestamp'], 'verbose_name': 'solicitação', 'verbose_name_plural': 'solicitações'},
        ),
    ]
