# Generated by Django 4.2.4 on 2023-09-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middleware", "0004_alter_historicalsolicitacao_recebido_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
                create or replace function is_valid_json(p_json text)
                    returns boolean
                as
                $$
                begin
                    return (p_json::json is not null);
                    exception
                        when others then
                            return false;
                end;
                $$
                language plpgsql
                immutable;
            """
        ),
        migrations.RunSQL(
            """
            UPDATE middleware_historicalsolicitacao
            SET
                recebido=CASE WHEN not is_valid_json(recebido) THEN '{}' ELSE recebido END,
                enviado=CASE WHEN not is_valid_json(enviado) THEN '{}' ELSE enviado END,
                respondido=CASE WHEN not is_valid_json(respondido) THEN '{}' ELSE respondido END
            """
        ),
        migrations.RunSQL(
            """
            UPDATE middleware_solicitacao
            SET
                recebido=CASE WHEN not is_valid_json(recebido) THEN '{}' ELSE recebido END,
                enviado=CASE WHEN not is_valid_json(enviado) THEN '{}' ELSE enviado END,
                respondido=CASE WHEN not is_valid_json(respondido) THEN '{}' ELSE respondido END
            """
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="recebido",
            field=models.JSONField(blank=True, null=True, verbose_name="JSON recebido"),
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="enviado",
            field=models.JSONField(blank=True, null=True, verbose_name="JSON enviado"),
        ),
        migrations.AlterField(
            model_name="historicalsolicitacao",
            name="respondido",
            field=models.JSONField(blank=True, null=True, verbose_name="JSON respondido"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="recebido",
            field=models.JSONField(blank=True, null=True, verbose_name="JSON recebido"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="enviado",
            field=models.JSONField(blank=True, null=True, verbose_name="JSON enviado"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="respondido",
            field=models.JSONField(blank=True, null=True, verbose_name="JSON respondido"),
        ),
    ]
