#!/usr/bin/env bash
source _/functions
source ./confs/enabled/dbfake.env

echo_info "Aguardando a base de dados..."
until _/$SERVICE_NAME/exec psql -U $POSTGRES_USER -d $POSTGRES_DATABASE -A -c '\l'>/dev/null 2>&1; do
  E=$(docker-compose logs --tail 1 $SERVICE_NAME | tail -1)
  echo_warning "Postgres is unavailable - sleeping. ERROR: $E"
  sleep 1
done

echo_success "Conectado com sucesso"
