# Generated by Django 4.0.5 on 2022-06-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_inscricao_polo'),
        ('a4', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.curso', verbose_name='curso do aluno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='polo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.polo', verbose_name='pólo do aluno'),
        ),
    ]
