# Generated by Django 4.2.1 on 2023-06-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4", "0003_alter_usuario_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="email_escolar",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nome_apresentacao",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nome_civil",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="tipo",
        ),
        migrations.AddField(
            model_name="usuario",
            name="email_google_classroom",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="e-Mail Gogole Classroom",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="URL da foto"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nome",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="nome no SUAP"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nome_registro",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="nome civil"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nome_usual",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="nome de apresentação",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="tipo"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email_corporativo",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="e-Mail corporativo"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome_social",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="nome social"
            ),
        ),
    ]
