# Generated by Django 4.1.3 on 2022-11-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="e-Mail preferêncial"),
        ),
    ]
