# Generated by Django 4.2.4 on 2023-08-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4", "0005_alter_grupo_managers_alter_usuario_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalusuario",
            name="last_json",
            field=models.TextField(blank=True, null=True, verbose_name="último JSON"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="last_json",
            field=models.TextField(blank=True, null=True, verbose_name="último JSON"),
        ),
    ]
