# Generated by Django 4.2.3 on 2023-08-01 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("painel", "0009_cohort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalvinculocurso",
            name="colaborador",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={
                    "tipo_usuario__in": [
                        "Servidor (Docente)",
                        "Servidor (Técnico-Administrativo)",
                        "Prestador de Serviço",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalvinculocurso",
            name="papel",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"contexto": "c"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="painel.papel",
            ),
        ),
        migrations.AlterField(
            model_name="historicalvinculopolo",
            name="colaborador",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={
                    "tipo_usuario__in": [
                        "Servidor (Docente)",
                        "Servidor (Técnico-Administrativo)",
                        "Prestador de Serviço",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vinculocurso",
            name="colaborador",
            field=models.ForeignKey(
                limit_choices_to={
                    "tipo_usuario__in": [
                        "Servidor (Docente)",
                        "Servidor (Técnico-Administrativo)",
                        "Prestador de Serviço",
                    ]
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vinculos_cursos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vinculocurso",
            name="papel",
            field=models.ForeignKey(
                limit_choices_to={"contexto": "c"},
                on_delete=django.db.models.deletion.PROTECT,
                to="painel.papel",
            ),
        ),
        migrations.AlterField(
            model_name="vinculopolo",
            name="colaborador",
            field=models.ForeignKey(
                limit_choices_to={
                    "tipo_usuario__in": [
                        "Servidor (Docente)",
                        "Servidor (Técnico-Administrativo)",
                        "Prestador de Serviço",
                    ]
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vinculos_polos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
