# Generated by Django 4.2.3 on 2023-08-01 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("painel", "0010_alter_historicalvinculocurso_colaborador_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="papel",
            options={
                "ordering": ["nome"],
                "verbose_name": "papel",
                "verbose_name_plural": "papéis",
            },
        ),
    ]
