# Generated by Django 4.0.4 on 2022-04-29 22:38

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do ambiente')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'ambiente',
                'verbose_name_plural': 'ambientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do campus no SUAP')),
                ('sigla', models.CharField(max_length=255, unique=True, verbose_name='sigla do campus')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('thumbnail', models.ImageField(max_length=255, upload_to='', verbose_name='thumbnail')),
                ('active', models.BooleanField(verbose_name='ativo?')),
                ('homepage', models.BooleanField(default=True, verbose_name='listar na página principal?')),
            ],
            options={
                'verbose_name': 'campus',
                'verbose_name_plural': 'campi',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do componente no SUAP')),
                ('sigla', models.CharField(max_length=255, unique=True, verbose_name='sigla do componente')),
                ('descricao', models.CharField(max_length=512, verbose_name='descrição')),
                ('descricao_historico', models.CharField(max_length=512, verbose_name='descrição no histórico')),
                ('periodo', models.IntegerField(blank=True, null=True, verbose_name='período')),
                ('tipo', models.IntegerField(verbose_name='tipo')),
                ('optativo', models.BooleanField(verbose_name='optativo')),
                ('qtd_avaliacoes', models.IntegerField(verbose_name='qtd. avalições')),
            ],
            options={
                'verbose_name': 'componente',
                'verbose_name_plural': 'componentes',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do curso no SUAP')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='código do curso')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do curso')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('url_ppc', models.URLField(max_length=255, verbose_name='URL')),
                ('thumbnail', models.ImageField(max_length=255, upload_to='', verbose_name='thumbnail')),
                ('active', models.BooleanField(verbose_name='ativo?')),
                ('homepage', models.BooleanField(default=True, verbose_name='listar na página principal?')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('ano_mes', models.IntegerField(primary_key=True, serialize=False, verbose_name='período')),
            ],
            options={
                'verbose_name': 'período',
                'verbose_name_plural': 'períodos',
                'ordering': ['ano_mes'],
            },
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do pólo no SUAP')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='nome do pólo')),
            ],
            options={
                'verbose_name': 'pólo',
                'verbose_name_plural': 'pólos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID da turma no SUAP')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='código da turma')),
                ('semestre', models.SmallIntegerField(verbose_name='semestre')),
                ('sigla', models.CharField(max_length=8, verbose_name='sigla da turma')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='avaportal.campus', verbose_name='campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaportal.curso', verbose_name='curso')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='avaportal.periodo', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='quando ocorreu')),
                ('requisicao', models.TextField(blank=True, null=True, verbose_name='requisição')),
                ('requisicao_header', models.TextField(blank=True, null=True, verbose_name='cabeçalho da requisição')),
                ('requisicao_invalida', models.TextField(blank=True, null=True, verbose_name='requisição inválida')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='resposta')),
                ('resposta_header', models.TextField(blank=True, null=True, verbose_name='cabeçalho da resposta')),
                ('resposta_invalida', models.TextField(blank=True, null=True, verbose_name='resposta inválida')),
                ('status', models.CharField(blank=True, choices=[('S', 'Sucesso'), ('F', 'Falha')], max_length=255, null=True, verbose_name='status')),
                ('status_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='status code')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaportal.campus')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', models.CharField(max_length=255, unique=True, verbose_name='ID do diário no SUAP')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='código do diário')),
                ('situacao', models.CharField(max_length=255, verbose_name='situação')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('descricao_historico', models.CharField(max_length=255, verbose_name='descrição no histórico')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaportal.componente', verbose_name='componente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaportal.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'diário',
                'verbose_name_plural': 'diários',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do usuário')),
                ('email_escolar', models.CharField(blank=True, max_length=255, null=True, verbose_name='e-Mail escolar')),
                ('email_academico', models.CharField(blank=True, max_length=255, null=True, verbose_name='e-Mail academico')),
                ('email_secundario', models.CharField(blank=True, max_length=255, null=True, verbose_name='e-Mail pessoal')),
                ('tipo', models.CharField(max_length=255, verbose_name='tipo')),
                ('first_login', models.DateTimeField(blank=True, null=True, verbose_name='first login')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='avaportal.campus', verbose_name='campus do aluno')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('polo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='avaportal.polo', verbose_name='pólo')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
