# Generated by Django 4.0.4 on 2022-04-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(blank=True, choices=[('N', 'Noturno'), ('V', 'Vespertino'), ('M', 'Matutino'), ('E', 'EAD'), ('D', 'Diurno'), ('I', 'Integral'), ('_', 'Desconhecido')], max_length=1, null=True, verbose_name='turno'),
        ),
    ]
