#!/usr/bin/env bash
source _/functions

if [[ `docker container ls | grep {$COMPOSE_PROJECT_NAME}_{$SERVICE_NAME}_1` ]]; then 
  _/$SERVICE_NAME/exec ./manage.py $@
else
  _/$SERVICE_NAME/run ./manage.py $@
fi
